apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unifi-cert
  namespace: unifi-controller
spec:
  secretName: unifi-secret
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  commonName: unifi.unifiedconsulting.net
  dnsNames:
  - unifi.unifiedconsulting.net
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
