apiVersion: v1
kind: Namespace
metadata:
  name: openvpn

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: openvpn-deployment
  namespace: openvpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openvpn
  template:
    metadata:
      labels:
        app: openvpn
    spec:
      containers:
        - name: openvpn
          image: ixdotai/openvpn
          ports:
            - containerPort: 1194
          volumeMounts:
            - name: openvpn-data
              mountPath: /etc/openvpn
          env:
            - name: EASYRSA_REQ_COUNTRY
              value: "US"
            - name: EASYRSA_REQ_PROVINCE
              value: "California"
            - name: EASYRSA_REQ_CITY
              value: "San Francisco"
            - name: EASYRSA_REQ_ORG
              value: "OpenVPN"
            - name: EASYRSA_REQ_EMAIL
              value: "admin@example.com"
            - name: EASYRSA_REQ_OU
              value: "IT"
            - name: EASYRSA_SERVER_NAME
              value: "OpenVPNServer"
            - name: RADIUS_SERVER
              value: "admin.unifiedconsulting.net"
            - name: RADIUS_SECRET
              value: "XXXXXXXX"
            - name: OVPN_DATA
              value: "/etc/openvpn" 
      volumes:
        - name: openvpn-data
          emptyDir: {}
---

apiVersion: v1
kind: Service
metadata:
  name: openvpn-service
  namespace: openvpn
spec:
  selector:
    app: openvpn
  ports:
    - name: port-1194
      protocol: TCP
      port: 1194
      targetPort: 1194
  type: LoadBalancer

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openvpn-ingress
  namespace: openvpn
spec:
  tls:
    - hosts:
        - openvpn.unifiedconsulting.net # replace with your domain name
      secretName: openvpn-tls # replace with your SSL certificate secret name
  rules:
    - host: openvpn.unifiedconsulting.net # replace with your domain name
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: openvpn-service
                port:
                  number: 1194
