apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: doh-cert
  namespace: dns
spec:
  secretName: doh-secret
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  commonName: doh.unifiedconsulting.net
  dnsNames:
  - doh.unifiedconsulting.net
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
