apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-cert
  namespace: bitwarden
spec:
  secretName: bitwarden-cert
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  commonName: bitwarden.unifiedconsulting.net
  dnsNames:
  - bitwarden.unifiedconsulting.net
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
