apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-pv
  namespace: dns
spec:
  capacity:
    storage: 2Gi  # Specify the desired storage capacity for your Grafana PV
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn  # Specify the storage class name used by Longhorn
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: driver.longhorn.io
    volumeHandle: pihole-pv  # Specify a unique identifier for the PV
    fsType: ext4  # Specify the desired file system type
    volumeAttributes:
      numberOfReplicas: "1"
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-pvc
  namespace: dns  # Specify the namespace where Grafana is deployed
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn  # Specify the storage class name used by Longhorn
  resources:
    requests:
      storage: 2Gi
