apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pihole-cert
  namespace: dns
spec:
  secretName: pihole-secret
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  commonName: pihole.unifiedconsulting.net
  dnsNames:
  - pihole.unifiedconsulting.net
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
