---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid-proxy
  namespace: squid-proxy
spec:
  selector:
    matchLabels:
      app: squid-proxy
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: squid-proxy
        tier: frontend
    spec:
      initContainers:
        - name: set-permissions
          image: busybox
          command: ["sh", "-c", "chmod -R 777 /var/cache/squid && chmod -R 777 /var/log/squid && sleep 3 && chown -R root:root /var/log/"]
          securityContext:
            runAsUser: 0
            privileged: true
          volumeMounts:
            - name: cache-volume
              mountPath: /var/cache/squid
            - name: log-volume
              mountPath: /var/log/squid
      containers:
        - name: squid-proxy
          image: jfxs/alpine-squid:latest
          command: ["squid"]
          args: ["-N"]
          ports:
            - containerPort: 3128
          volumeMounts:
            - name: cache-volume
              mountPath: /var/cache/squid
            - name: log-volume
              mountPath: /var/log/squid
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
            privileged: true
      volumes:
        - name: cache-volume
          emptyDir: {}
        - name: log-volume
          hostPath:
            path: /var/log/squid/access.log
