apiVersion: v1
kind: Service
metadata:
  labels:
    app: squid-proxy
    tier: frontend
  name: squid-proxy-service
spec:
  selector:
    app: squid-proxy
    tier: frontend
  ports:
    - protocol: TCP
      port: 3128
      targetPort: 3128
      nodePort: 31280
  type: NodePort
