apiVersion: v1
kind: Service
metadata:
  namespace: dns
  name: unbound
spec:
  clusterIP: 10.43.0.53
  selector:
    app: unbound
  ports:
    - name: dns
      protocol: UDP
      port: 53
      targetPort: 53
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
