apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openconnect-cert
  namespace: openconnect
spec:
  secretName: opencpnnect-secret
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  commonName: cisco.unifiedconsulting.net
  dnsNames:
  - cisco.unifiedconsulting.net
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
