kind: Deployment
apiVersion: apps/v1
metadata:
  name: mikrotik
  namespace: mikrotik
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mikrotik
  template:
    metadata:
      name: mikrotik
      labels:
        name: mikrotik
    spec:
      containers:
        - name: mikrotik
          image: '1247004718/routeros-aarch64:6.48.1-stable'
          ports:
            - containerPort: 22
              protocol: TCP
            - containerPort: 443
              protocol: TCP
            - containerPort: 8291
              protocol: TCP
            - containerPort: 80
              protocol: TCP
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
            privileged: true

