apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring  # Specify the namespace where Grafana is deployed
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn  # Specify the storage class name used by Longhorn
  resources:
    requests:
      storage: 2Gi
