apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-cert
  namespace: monitoring
spec:
  secretName: prometheus-secret
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  commonName: prometheus.unifiedconsulting.net
  dnsNames:
  - prometheus.unifiedconsulting.net
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
